[watch]
watch = ["./src"]

[serve]
addresses = ["127.0.0.1"]
port = 8080
open = false

# Proxy pour les appels API vers le backend
[[proxy]]
rewrite = "/api"
backend = "http://hangar.garageisep.com/api"
#backend = "http://hangar.localhost/api"